source 'https://rubygems.org'

gem 'mechanize'
gem 'colorize', '~> 0.7.7'
gem 'rspec'
gem 'rails_best_practices'
gem 'rubocop', '~> 0.39'
gem 'rubocop-rspec'
gem 'brakeman', '3.2.1'
gem 'simplecov'
gem 'figaro'
gem 'scss_lint'
gem 'parallel'
gem 'bugsnag'
group :test do
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-support'
  gem 'nokogiri'
  gem 'equivalent-xml'
  gem 'pry'
  gem 'pry-nav'
end
